---
Description:
  Matheus Liberato / Udacity Capstone
  This script create a kubernetes cluster using network resources
  provided by network-stack script.

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resouces.
    Type: String

Resources:

  ClusterRole:
    Description: Allows EKS to manage clusters on your behalf.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
            Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  ClusterControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"

  Cluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Version: "1.13"
      RoleArn: !GetAtt ClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterControlPlaneSecurityGroup
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PRI1-SN"
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PRI2-SN"
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PUB1-SN"
          - Fn::ImportValue:
              !Sub "${EnvironmentName}-PUB2-SN"

Outputs:
  ClusterName:
    Description: Cluster Name
    Value: !Ref Cluster
    Export:
      Name: !Sub ${EnvironmentName}-CLUSTER-NAME

  ClusterArn:
    Description: Cluster Arn
    Value: !GetAtt Cluster.Arn
    Export:
      Name: !Sub ${EnvironmentName}-CLUSTER-ARN

  ClusterEndpoint:
    Description: Cluster Endpoint
    Value: !GetAtt Cluster.Endpoint
    Export:
      Name: !Sub ${EnvironmentName}-CLU-ENDP

  ClusterControlPlaneSecurityGroup:
    Description: ClusterControlPlaneSecurityGroup
    Value: !Ref ClusterControlPlaneSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-CLUS-CONT-PLAN-SC

